Categories:
  - Navigation
License: GPL-3.0-only
AuthorName: Christophe Savary
AuthorEmail: christophesavary@martoweb.com
WebSite: https://martoweb.com
SourceCode: https://github.com/Smartoweb/Roadscript
IssueTracker: https://github.com/Smartoweb/Roadscript/issues

AutoName: Roadscript
Summary: Suivez l'entretien et la consommation de votre véhicule
Description: |-
  Roadscript est votre compagnon de route indispensable pour centraliser et
  gérer l'historique complet de votre véhicule. Cette application Android
  open-source vous permet de suivre vos interventions, d'archiver vos
  documents importants et de garder un œil précis sur votre carnet
  d'entretien numérique.

RepoType: git
Repo: https://github.com/Smartoweb/Roadscript.git

Builds:
  - versionName: '1.0'
    versionCode: 1
    commit: v1.0
    subdir: app
    sudo: apt-get update && apt-get install -y openjdk-21-jdk
    gradle:
      - yes

AllowedAPKSigningKeys:
  - debdc2d9aa1ad95ab25ff74c5bbe7c431568fb4f431895c09a4a0dfe30a0cf58

Binaries: https://github.com/Smartoweb/Roadscript/releases/download/v1.0/Roadscript.apk

AutoUpdateMode: None
UpdateCheckMode: Tags
CurrentVersion: '1.0'
CurrentVersionCode: 1
